# Generated by Django 3.1.1 on 2020-11-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playcity',
            name='bot_word',
            field=models.CharField(max_length=250, null=True, verbose_name='Слово Бота'),
        ),
        migrations.AlterField(
            model_name='playcity',
            name='error_user_word',
            field=models.CharField(max_length=250, null=True, verbose_name='Не правильное слово'),
        ),
        migrations.AlterField(
            model_name='playcity',
            name='user_word',
            field=models.CharField(max_length=150, null=True, verbose_name='Слово пользователя'),
        ),
    ]
