# Generated by Django 3.1.1 on 2020-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201108_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='playcity',
            name='count_word',
            field=models.IntegerField(null=True, verbose_name='Количество слов'),
        ),
    ]
