# Generated by Django 3.1.1 on 2020-11-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playcity_count_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='playcity',
            name='error_start_word',
            field=models.CharField(max_length=250, null=True, verbose_name='Начинается не с той буквы'),
        ),
    ]
