# Generated by Django 3.1.1 on 2020-11-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201109_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listfilmsactor',
            options={'verbose_name': 'Список фильмов и актеров', 'verbose_name_plural': 'Список фильмов и актеров'},
        ),
    ]
